"""add_ns_post

Revision ID: 5606760f5fcf
Revises: d54dedfe564e
Create Date: 2024-08-19 18:51:46.707745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5606760f5fcf'
down_revision = 'd54dedfe564e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nsfw', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercontent', schema=None) as batch_op:
        batch_op.drop_column('nsfw')
        batch_op.drop_column('post')

    # ### end Alembic commands ###
