"""avatar

Revision ID: 84b34edb6d7f
Revises: bacd9fd062c4
Create Date: 2024-08-13 22:53:00.758130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84b34edb6d7f'
down_revision = 'bacd9fd062c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=50), nullable=True))
        batch_op.alter_column('about_me',
               existing_type=mysql.VARCHAR(length=140),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
