"""add_content_links2

Revision ID: d35a1e1d1d9d
Revises: 1e6c733b7acd
Create Date: 2024-08-18 03:43:57.745802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd35a1e1d1d9d'
down_revision = '1e6c733b7acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercontent', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercontent', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
